name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Ninja & LLD
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build lld
    - name: Build
      run: |
        cmake -S . -B build --preset=default -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_CXX_COMPILER=/usr/bin/gcc -DCMAKE_CPP_COMPILER=/usr/bin/g++
        ninja -v -C ./build
